<a href="https://colab.research.google.com/github/harshdsdh/MLstuff/blob/master/knn_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn import datasets
iris = datasets.load_iris()

In [44]:
iris

<function sklearn.datasets._base.load_iris>

In [0]:
X = iris.data[:,:]
y=iris.target

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [0]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test  = scaler.transform(X_test)

In [0]:
y_test

In [0]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)



In [55]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[ 4  0  0]
 [ 0 10  0]
 [ 0  2 14]]


In [58]:
acc=0
s=0
for i in range(len(y_test)):
  if y_test[i]==y_pred[i]:
    s+=1
print (s/len(y_test))
    

0.9333333333333333


In [59]:
import numpy as np
print(np.mean(y_pred==y_test))

0.9333333333333333
